"""second

Revision ID: 302f8572ec63
Revises: 644e669c5e0c
Create Date: 2017-09-12 22:30:40.903717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302f8572ec63'
down_revision = '644e669c5e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('use_avatar', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'use_avatar')
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###
